version: "3.9"
services:
  # Здесь позже добавим postgres, minio, redis, backup и т.д.
  # Пример см. в предыдущих шагах.
  placeholder:
    image: alpine:3.20
    command: ["sh","-c","echo 'infra placeholder'; sleep 3600"]
    restart: unless-stopped
