spring:
  r2dbc:
    url: ${AUDIT_R2DBC_URL}
    username: ${AUDIT_DB_USER}
    password: ${AUDIT_DB_PASSWORD}
  datasource:
    url: ${AUDIT_JDBC_URL}
    username: ${AUDIT_DB_USER}
    password: ${AUDIT_DB_PASSWORD}
    hikari:
      schema: ${AUDIT_DB_SCHEMA:audit}
  cloud:
    stream:
      bindings:
        auditEventsConsumer-in-0:
          consumer:
            maxAttempts: 1
        auditCoreConsumer-in-0:
          consumer:
            maxAttempts: 1

audit:
  messaging:
    prefetch: 20
