spring:
  config:
    activate:
      on-profile: local
  r2dbc:
    url: ${PAYMENTS_R2DBC_URL}
    username: ${PAYMENTS_DB_USER}
    password: ${PAYMENTS_DB_PASSWORD}
  flyway:
    enabled: true
    url: ${PAYMENTS_JDBC_URL:${PAYMENTS_DATABASE_URL}}
    user: ${PAYMENTS_DB_USER}
    password: ${PAYMENTS_DB_PASSWORD}
    default-schema: payments
    locations: classpath:db/migration
  rabbitmq:
    uri: ${PAYMENTS_RABBITMQ_URL}

logging:
  level:
    root: INFO
    com.crm.payments: DEBUG

payments:
  exports:
    queue: ${PAYMENTS_EXPORTS_QUEUE:payments.exports}
    status-queue: ${PAYMENTS_EXPORTS_STATUS_QUEUE:payments.exports.status}
    storage:
      bucket: ${PAYMENTS_EXPORTS_STORAGE_BUCKET:}
      prefix: ${PAYMENTS_EXPORTS_STORAGE_PREFIX:payments/exports}
      base-url: ${PAYMENTS_EXPORTS_STORAGE_BASE_URL:}
      url-ttl: ${PAYMENTS_EXPORTS_STORAGE_URL_TTL:PT24H}
  crm:
    webhook:
      secret: ${PAYMENTS_CRM_WEBHOOK_SECRET:}
