apiVersion: v1
kind: Secret
metadata:
  name: backup-secret
  namespace: crm
  labels:
    app.kubernetes.io/name: backup
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: crm-platform
stringData:
  BACKUP_DATABASE_URL: "postgresql://backup:backup@postgres:5432/crm?options=-csearch_path%3Dbackup"
  BACKUP_POSTGRES_BACKUP_DSN: "postgresql://postgres:postgres@postgres:5432/crm"
  BACKUP_S3_ENDPOINT_URL: "http://minio:9000"
  BACKUP_S3_REGION_NAME: "us-east-1"
  BACKUP_S3_BUCKET: "crm-backups"
  BACKUP_S3_ACCESS_KEY: "change_me"
  BACKUP_S3_SECRET_KEY: "change_me"
  BACKUP_RABBITMQ_URL: "amqp://crm:crm@rabbitmq:5672/crm"
  BACKUP_RABBITMQ_MANAGEMENT_URL: "http://rabbitmq:15672"
  BACKUP_RABBITMQ_ADMIN_USER: "crm"
  BACKUP_RABBITMQ_ADMIN_PASSWORD: "crm"
  BACKUP_RABBITMQ_VHOST: "crm"
  BACKUP_CONSUL_HTTP_ADDR: "http://consul:8500"
  BACKUP_CONSUL_TOKEN: ""
  BACKUP_REDIS_HOST: "redis"
  BACKUP_REDIS_PORT: "6379"
  BACKUP_REDIS_PASSWORD: ""
  BACKUP_REDIS_DATA_DIR: "/data"
