apiVersion: apps/v1
kind: Deployment
metadata:
  name: backup
  namespace: crm
  labels:
    app.kubernetes.io/name: backup
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: crm-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: backup
  template:
    metadata:
      labels:
        app.kubernetes.io/name: backup
        app.kubernetes.io/component: service
        app.kubernetes.io/part-of: crm-platform
    spec:
      containers:
        - name: backup
          image: ghcr.io/your-org/crm-backup:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: backup-config
            - secretRef:
                name: backup-secret
          ports:
            - containerPort: 8094
              name: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 30
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
