apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/component: api
    app.kubernetes.io/instance: gateway
    app.kubernetes.io/part-of: crm-platform
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/instance: gateway
  ports:
    - name: http
      port: 80
      targetPort: http
