apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
data:
  # Stage использует отдельный HTTPS-хост; отразите фактический домен Gateway при деплое.
  CONSUL_HTTP_ADDR: "http://consul.stage.svc.cluster.local:8500"
  REDIS_URL: "redis://stage-redis:6379/0"
