apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
data:
  # Прод использует публичный HTTPS-домен; замените значения на реальные URLы Gateway.
  CONSUL_HTTP_ADDR: "https://consul.internal.crm.company"
  REDIS_URL: "redis://prod-redis:6379/0"
