CREATE SCHEMA IF NOT EXISTS payments;
CREATE SCHEMA IF NOT EXISTS crm;
CREATE SCHEMA IF NOT EXISTS auth;

CREATE TABLE IF NOT EXISTS crm.deals (
    id UUID PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS crm.policies (
    id UUID PRIMARY KEY,
    deal_id UUID
);

CREATE TABLE IF NOT EXISTS auth.users (
    id UUID PRIMARY KEY
);
